function getData() {
    const data = [
        {
            npk: "100",
            nama: "Melanie Gutierrez",
            no_hp: "+6285928169289",
            email: "melaniegutierrez@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2019-05-14",
            status: "active",
        },
        {
            npk: "101",
            nama: "Ori Leblanc",
            no_hp: "+6289557644788",
            email: "orileblanc@aiia.id",
            alamat: "Ambon",
            tgl_masuk: "2018-05-21",
            status: "nonactive",
        },
        {
            npk: "102",
            nama: "Hall Conway",
            no_hp: "+6280853218565",
            email: "hallconway@aiia.id",
            alamat: "Mamuju",
            tgl_masuk: "2018-01-20",
            status: "active",
        },
        {
            npk: "103",
            nama: "Bernard Henson",
            no_hp: "+6280352411755",
            email: "bernardhenson@aiia.id",
            alamat: "Bengkulu",
            tgl_masuk: "2016-06-11",
            status: "active",
        },
        {
            npk: "104",
            nama: "Idona Rutledge",
            no_hp: "+6289758538785",
            email: "idonarutledge@aiia.co",
            alamat: "Banjarbaru",
            tgl_masuk: "2022-07-13",
            status: "nonactive",
        },
        {
            npk: "105",
            nama: "Chandler Norman",
            no_hp: "+6281468522889",
            email: "chandlernorman@aiia.id",
            alamat: "Sukabumi",
            tgl_masuk: "2015-12-03",
            status: "active",
        },
        {
            npk: "106",
            nama: "Audrey Moses",
            no_hp: "+6288132147115",
            email: "audreymoses@aiia.co",
            alamat: "Tasikmalaya",
            tgl_masuk: "2022-08-09",
            status: "nonactive",
        },
        {
            npk: "107",
            nama: "Idona Clayton",
            no_hp: "+6286214646766",
            email: "idonaclayton7462@aiia.id",
            alamat: "Sungai Penuh",
            tgl_masuk: "2020-04-21",
            status: "active",
        },
        {
            npk: "108",
            nama: "Beatrice Bell",
            no_hp: "+6284111588915",
            email: "beatricebell@aiia.id",
            alamat: "Tual",
            tgl_masuk: "2018-07-21",
            status: "active",
        },
        {
            npk: "109",
            nama: "Xena Riddle",
            no_hp: "+6282677044368",
            email: "xenariddle@aiia.co",
            alamat: "Semarang",
            tgl_masuk: "2019-08-19",
            status: "active",
        },
        {
            npk: "110",
            nama: "Amela Beard",
            no_hp: "+6283126017584",
            email: "amelabeard@aiia.id",
            alamat: "Manokwari",
            tgl_masuk: "2018-04-21",
            status: "active",
        },
        {
            npk: "111",
            nama: "Maggie Pruitt",
            no_hp: "+6284128398864",
            email: "maggiepruitt@aiia.co",
            alamat: "Bandar Lampung",
            tgl_masuk: "2016-08-31",
            status: "active",
        },
        {
            npk: "112",
            nama: "Lyle Moss",
            no_hp: "+6281858821177",
            email: "lylemoss8231@aiia.co",
            alamat: "Singkawang",
            tgl_masuk: "2024-04-06",
            status: "nonactive",
        },
        {
            npk: "113",
            nama: "Xaviera Nixon",
            no_hp: "+6281744756868",
            email: "xavieranixon@aiia.co",
            alamat: "Bontang",
            tgl_masuk: "2022-02-16",
            status: "active",
        },
        {
            npk: "114",
            nama: "Kimberly Kent",
            no_hp: "+6287584841574",
            email: "kimberlykent@aiia.id",
            alamat: "Tasikmalaya",
            tgl_masuk: "2022-12-11",
            status: "active",
        },
        {
            npk: "115",
            nama: "Fritz Cantrell",
            no_hp: "+6281247395947",
            email: "fritzcantrell@aiia.co",
            alamat: "Banjarbaru",
            tgl_masuk: "2017-01-16",
            status: "active",
        },
        {
            npk: "116",
            nama: "Ebony Sullivan",
            no_hp: "+6282201427768",
            email: "ebonysullivan@aiia.co",
            alamat: "Bandung",
            tgl_masuk: "2018-10-29",
            status: "nonactive",
        },
        {
            npk: "117",
            nama: "Valentine Cook",
            no_hp: "+6282375131245",
            email: "valentinecook3698@aiia.id",
            alamat: "Manado",
            tgl_masuk: "2018-04-27",
            status: "active",
        },
        {
            npk: "118",
            nama: "Sara Francis",
            no_hp: "+6284241781558",
            email: "sarafrancis@aiia.co",
            alamat: "Tidore",
            tgl_masuk: "2016-03-08",
            status: "active",
        },
        {
            npk: "119",
            nama: "Sierra Acevedo",
            no_hp: "+6283773146183",
            email: "sierraacevedo@aiia.id",
            alamat: "Ternate",
            tgl_masuk: "2016-02-05",
            status: "active",
        },
        {
            npk: "120",
            nama: "Alexandra Nieves",
            no_hp: "+6288574128893",
            email: "alexandranieves6424@aiia.co",
            alamat: "Yogyakarta",
            tgl_masuk: "2021-12-29",
            status: "nonactive",
        },
        {
            npk: "121",
            nama: "Sacha Morrow",
            no_hp: "+6286975293128",
            email: "sachamorrow@aiia.co",
            alamat: "Mamuju",
            tgl_masuk: "2019-04-27",
            status: "active",
        },
        {
            npk: "122",
            nama: "Cameron Leon",
            no_hp: "+6288223968932",
            email: "cameronleon1471@aiia.co",
            alamat: "Bontang",
            tgl_masuk: "2019-02-10",
            status: "active",
        },
        {
            npk: "123",
            nama: "Keaton Sosa",
            no_hp: "+6284469283798",
            email: "keatonsosa@aiia.co",
            alamat: "Jambi",
            tgl_masuk: "2017-10-18",
            status: "nonactive",
        },
        {
            npk: "124",
            nama: "Jason Manning",
            no_hp: "+6280635366043",
            email: "jasonmanning214@aiia.id",
            alamat: "Jayapura",
            tgl_masuk: "2020-05-27",
            status: "active",
        },
        {
            npk: "125",
            nama: "Jerome Wagner",
            no_hp: "+6285462178331",
            email: "jeromewagner@aiia.id",
            alamat: "Manokwari",
            tgl_masuk: "2015-10-30",
            status: "nonactive",
        },
        {
            npk: "126",
            nama: "Justin Ramsey",
            no_hp: "+6281517958448",
            email: "justinramsey@aiia.id",
            alamat: "Cirebon",
            tgl_masuk: "2016-02-09",
            status: "nonactive",
        },
        {
            npk: "127",
            nama: "Jack Carson",
            no_hp: "+6280566012437",
            email: "jackcarson2404@aiia.id",
            alamat: "Pematangsiantar",
            tgl_masuk: "2019-07-27",
            status: "nonactive",
        },
        {
            npk: "128",
            nama: "Hop Cole",
            no_hp: "+6281569116226",
            email: "hopcole7637@aiia.co",
            alamat: "Ambon",
            tgl_masuk: "2017-04-05",
            status: "active",
        },
        {
            npk: "129",
            nama: "Price Nieves",
            no_hp: "+6281004416559",
            email: "pricenieves@aiia.co",
            alamat: "Tebing Tinggi",
            tgl_masuk: "2021-03-31",
            status: "nonactive",
        },
        {
            npk: "130",
            nama: "Elton Mcclure",
            no_hp: "+6288728134367",
            email: "eltonmcclure2859@aiia.id",
            alamat: "Tanjung Pinang",
            tgl_masuk: "2019-09-23",
            status: "nonactive",
        },
        {
            npk: "131",
            nama: "Valentine Flores",
            no_hp: "+6284084639678",
            email: "valentineflores@aiia.co",
            alamat: "Mamuju",
            tgl_masuk: "2022-04-08",
            status: "nonactive",
        },
        {
            npk: "132",
            nama: "Leo Pate",
            no_hp: "+6284831381628",
            email: "leopate@aiia.id",
            alamat: "Palu",
            tgl_masuk: "2017-05-14",
            status: "nonactive",
        },
        {
            npk: "133",
            nama: "Nola Finch",
            no_hp: "+6284895362222",
            email: "nolafinch@aiia.id",
            alamat: "Palangka Raya",
            tgl_masuk: "2020-12-03",
            status: "nonactive",
        },
        {
            npk: "134",
            nama: "Daniel Lucas",
            no_hp: "+6281917288717",
            email: "daniellucas@aiia.id",
            alamat: "Pekanbaru",
            tgl_masuk: "2021-09-30",
            status: "nonactive",
        },
        {
            npk: "135",
            nama: "Lunea Stephens",
            no_hp: "+6285013454636",
            email: "luneastephens4654@aiia.co",
            alamat: "Sawahlunto",
            tgl_masuk: "2018-01-24",
            status: "nonactive",
        },
        {
            npk: "136",
            nama: "Bryar Leon",
            no_hp: "+6280557218142",
            email: "bryarleon9013@aiia.co",
            alamat: "Gorontalo",
            tgl_masuk: "2021-09-28",
            status: "active",
        },
        {
            npk: "137",
            nama: "Herrod Vang",
            no_hp: "+6280153476698",
            email: "herrodvang@aiia.co",
            alamat: "Surabaya",
            tgl_masuk: "2015-12-03",
            status: "nonactive",
        },
        {
            npk: "138",
            nama: "Jena Parrish",
            no_hp: "+6281122834533",
            email: "jenaparrish@aiia.id",
            alamat: "Sungai Penuh",
            tgl_masuk: "2017-04-30",
            status: "active",
        },
        {
            npk: "139",
            nama: "Azalia Castro",
            no_hp: "+6283464185613",
            email: "azaliacastro@aiia.id",
            alamat: "Kupang",
            tgl_masuk: "2019-08-31",
            status: "active",
        },
        {
            npk: "140",
            nama: "Virginia Goodwin",
            no_hp: "+6287216561557",
            email: "virginiagoodwin@aiia.id",
            alamat: "Serang",
            tgl_masuk: "2019-02-20",
            status: "nonactive",
        },
        {
            npk: "141",
            nama: "Nash Vang",
            no_hp: "+6283866502073",
            email: "nashvang9501@aiia.co",
            alamat: "Mataram",
            tgl_masuk: "2021-10-11",
            status: "nonactive",
        },
        {
            npk: "142",
            nama: "Summer Riddle",
            no_hp: "+6280725694564",
            email: "summerriddle5132@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2020-03-11",
            status: "active",
        },
        {
            npk: "143",
            nama: "Quemby Pate",
            no_hp: "+6282322479197",
            email: "quembypate2529@aiia.id",
            alamat: "Denpasar",
            tgl_masuk: "2020-09-16",
            status: "active",
        },
        {
            npk: "144",
            nama: "Lacey Reilly",
            no_hp: "+6288898232342",
            email: "laceyreilly2297@aiia.id",
            alamat: "Palu",
            tgl_masuk: "2023-10-02",
            status: "nonactive",
        },
        {
            npk: "145",
            nama: "Scott Moon",
            no_hp: "+6283427672431",
            email: "scottmoon@aiia.co",
            alamat: "Tual",
            tgl_masuk: "2021-06-15",
            status: "active",
        },
        {
            npk: "146",
            nama: "Talon Berger",
            no_hp: "+6284263947351",
            email: "talonberger5482@aiia.co",
            alamat: "Pangkalpinang",
            tgl_masuk: "2020-07-29",
            status: "nonactive",
        },
        {
            npk: "147",
            nama: "Kennan Booker",
            no_hp: "+6288822827682",
            email: "kennanbooker4300@aiia.id",
            alamat: "Gunungsitoli",
            tgl_masuk: "2021-02-17",
            status: "nonactive",
        },
        {
            npk: "148",
            nama: "Zane Rivers",
            no_hp: "+6283667049636",
            email: "zanerivers@aiia.id",
            alamat: "Mamuju",
            tgl_masuk: "2016-10-06",
            status: "nonactive",
        },
        {
            npk: "149",
            nama: "Damon Bradley",
            no_hp: "+6281541598374",
            email: "damonbradley9208@aiia.co",
            alamat: "Manado",
            tgl_masuk: "2018-06-23",
            status: "active",
        },
        {
            npk: "150",
            nama: "Hanna Whitley",
            no_hp: "+6283742468888",
            email: "hannawhitley240@aiia.co",
            alamat: "Manokwari",
            tgl_masuk: "2016-07-23",
            status: "active",
        },
        {
            npk: "151",
            nama: "Sydnee Clements",
            no_hp: "+6287144626116",
            email: "sydneeclements9580@aiia.id",
            alamat: "Binjai",
            tgl_masuk: "2023-10-18",
            status: "active",
        },
        {
            npk: "152",
            nama: "Adrienne Delaney",
            no_hp: "+6286884527321",
            email: "adriennedelaney8577@aiia.id",
            alamat: "Banjarbaru",
            tgl_masuk: "2021-03-19",
            status: "nonactive",
        },
        {
            npk: "153",
            nama: "Chantale Mitchell",
            no_hp: "+6287585989983",
            email: "chantalemitchell5795@aiia.co",
            alamat: "Tarakan",
            tgl_masuk: "2016-04-06",
            status: "active",
        },
        {
            npk: "154",
            nama: "Heather Paul",
            no_hp: "+6281477563639",
            email: "heatherpaul1316@aiia.id",
            alamat: "Padang",
            tgl_masuk: "2018-01-09",
            status: "nonactive",
        },
        {
            npk: "155",
            nama: "Christopher Bird",
            no_hp: "+6287546258523",
            email: "christopherbird9595@aiia.co",
            alamat: "Pekanbaru",
            tgl_masuk: "2019-01-29",
            status: "active",
        },
        {
            npk: "156",
            nama: "Cleo Bauer",
            no_hp: "+6282319187265",
            email: "cleobauer@aiia.id",
            alamat: "Pontianak",
            tgl_masuk: "2019-01-10",
            status: "active",
        },
        {
            npk: "157",
            nama: "Cheyenne Adkins",
            no_hp: "+6286849261697",
            email: "cheyenneadkins4712@aiia.co",
            alamat: "Denpasar",
            tgl_masuk: "2021-10-18",
            status: "nonactive",
        },
        {
            npk: "158",
            nama: "Sydnee Sampson",
            no_hp: "+6281211357775",
            email: "sydneesampson@aiia.id",
            alamat: "Palu",
            tgl_masuk: "2019-05-27",
            status: "nonactive",
        },
        {
            npk: "159",
            nama: "Blythe Bridges",
            no_hp: "+6281443216123",
            email: "blythebridges3407@aiia.co",
            alamat: "Ambon",
            tgl_masuk: "2022-07-11",
            status: "active",
        },
        {
            npk: "160",
            nama: "Constance Washington",
            no_hp: "+6284608404812",
            email: "constancewashington3631@aiia.id",
            alamat: "Surabaya",
            tgl_masuk: "2016-09-02",
            status: "active",
        },
        {
            npk: "161",
            nama: "Genevieve Walters",
            no_hp: "+6286135188210",
            email: "genevievewalters9774@aiia.co",
            alamat: "Semarang",
            tgl_masuk: "2018-08-17",
            status: "nonactive",
        },
        {
            npk: "162",
            nama: "Garth Singleton",
            no_hp: "+6285235514653",
            email: "garthsingleton3748@aiia.co",
            alamat: "Samarinda",
            tgl_masuk: "2022-06-06",
            status: "nonactive",
        },
        {
            npk: "163",
            nama: "Gwendolyn Parker",
            no_hp: "+6286518247638",
            email: "gwendolynparker3912@aiia.co",
            alamat: "Palangka Raya",
            tgl_masuk: "2015-12-17",
            status: "active",
        },
        {
            npk: "164",
            nama: "Zahir Young",
            no_hp: "+6281233749734",
            email: "zahiryoung1138@aiia.co",
            alamat: "Tasikmalaya",
            tgl_masuk: "2023-02-01",
            status: "nonactive",
        },
        {
            npk: "165",
            nama: "Abraham Salazar",
            no_hp: "+6284611256847",
            email: "abrahamsalazar4090@aiia.co",
            alamat: "Pangkalpinang",
            tgl_masuk: "2022-12-31",
            status: "active",
        },
        {
            npk: "166",
            nama: "Ross Merrill",
            no_hp: "+6287636151244",
            email: "rossmerrill6383@aiia.co",
            alamat: "Kupang",
            tgl_masuk: "2018-05-08",
            status: "nonactive",
        },
        {
            npk: "167",
            nama: "Sonya Morrow",
            no_hp: "+6286268434817",
            email: "sonyamorrow9175@aiia.id",
            alamat: "Jayapura",
            tgl_masuk: "2019-02-16",
            status: "active",
        },
        {
            npk: "168",
            nama: "Nehru Cummings",
            no_hp: "+6287528418851",
            email: "nehrucummings7984@aiia.id",
            alamat: "Bukittinggi",
            tgl_masuk: "2023-08-06",
            status: "active",
        },
        {
            npk: "169",
            nama: "Logan Hardy",
            no_hp: "+6287224059554",
            email: "loganhardy@aiia.id",
            alamat: "Baubau",
            tgl_masuk: "2021-05-25",
            status: "nonactive",
        },
        {
            npk: "170",
            nama: "Caldwell Parks",
            no_hp: "+6285756552647",
            email: "caldwellparks3279@aiia.id",
            alamat: "Semarang",
            tgl_masuk: "2022-10-24",
            status: "nonactive",
        },
        {
            npk: "171",
            nama: "Steel Bruce",
            no_hp: "+6289857392784",
            email: "steelbruce@aiia.co",
            alamat: "Bandar Lampung",
            tgl_masuk: "2019-01-11",
            status: "active",
        },
        {
            npk: "172",
            nama: "Jamal Wallace",
            no_hp: "+6283833351687",
            email: "jamalwallace8548@aiia.id",
            alamat: "Palembang",
            tgl_masuk: "2016-06-23",
            status: "active",
        },
        {
            npk: "173",
            nama: "Dante Fry",
            no_hp: "+6285170639666",
            email: "dantefry966@aiia.id",
            alamat: "Payakumbuh",
            tgl_masuk: "2016-11-11",
            status: "nonactive",
        },
        {
            npk: "174",
            nama: "Carl Huff",
            no_hp: "+6286377728442",
            email: "carlhuff5237@aiia.co",
            alamat: "Bitung",
            tgl_masuk: "2024-04-30",
            status: "active",
        },
        {
            npk: "175",
            nama: "Cade Hull",
            no_hp: "+6285872898434",
            email: "cadehull2224@aiia.co",
            alamat: "Gunungsitoli",
            tgl_masuk: "2023-02-19",
            status: "active",
        },
        {
            npk: "176",
            nama: "Phelan Rosales",
            no_hp: "+6285847773373",
            email: "phelanrosales9199@aiia.co",
            alamat: "North Jakarta",
            tgl_masuk: "2020-02-07",
            status: "active",
        },
        {
            npk: "177",
            nama: "Farrah Shannon",
            no_hp: "+6285272595282",
            email: "farrahshannon1225@aiia.id",
            alamat: "Bitung",
            tgl_masuk: "2024-04-27",
            status: "nonactive",
        },
        {
            npk: "178",
            nama: "Cameran Hammond",
            no_hp: "+6288016944336",
            email: "cameranhammond5688@aiia.co",
            alamat: "Bengkulu",
            tgl_masuk: "2020-12-28",
            status: "nonactive",
        },
        {
            npk: "179",
            nama: "Abigail Mooney",
            no_hp: "+6284234432636",
            email: "abigailmooney8678@aiia.id",
            alamat: "Banda Aceh",
            tgl_masuk: "2020-08-28",
            status: "nonactive",
        },
        {
            npk: "180",
            nama: "Cooper Branch",
            no_hp: "+6282668997223",
            email: "cooperbranch@aiia.id",
            alamat: "Semarang",
            tgl_masuk: "2020-11-11",
            status: "active",
        },
        {
            npk: "181",
            nama: "Justine Harmon",
            no_hp: "+6285233387672",
            email: "justineharmon8939@aiia.co",
            alamat: "Blitar",
            tgl_masuk: "2021-09-16",
            status: "active",
        },
        {
            npk: "182",
            nama: "Ruth Booker",
            no_hp: "+6283247416757",
            email: "ruthbooker786@aiia.co",
            alamat: "Banjarmasin",
            tgl_masuk: "2020-03-20",
            status: "nonactive",
        },
        {
            npk: "183",
            nama: "Nash Walter",
            no_hp: "+6284050510188",
            email: "nashwalter@aiia.id",
            alamat: "Bengkulu",
            tgl_masuk: "2017-05-06",
            status: "nonactive",
        },
        {
            npk: "184",
            nama: "Randall Erickson",
            no_hp: "+6282531403502",
            email: "randallerickson@aiia.id",
            alamat: "Dumai",
            tgl_masuk: "2023-10-17",
            status: "active",
        },
        {
            npk: "185",
            nama: "Breanna Cox",
            no_hp: "+6280297324216",
            email: "breannacox@aiia.id",
            alamat: "Palembang",
            tgl_masuk: "2015-10-07",
            status: "active",
        },
        {
            npk: "186",
            nama: "Dawn Combs",
            no_hp: "+6283810453973",
            email: "dawncombs484@aiia.co",
            alamat: "Manokwari",
            tgl_masuk: "2021-12-09",
            status: "active",
        },
        {
            npk: "187",
            nama: "Cassidy Richardson",
            no_hp: "+6288562885483",
            email: "cassidyrichardson@aiia.co",
            alamat: "Mamuju",
            tgl_masuk: "2024-02-28",
            status: "active",
        },
        {
            npk: "188",
            nama: "Zane Stewart",
            no_hp: "+6285709484438",
            email: "zanestewart1095@aiia.id",
            alamat: "Bima",
            tgl_masuk: "2020-10-29",
            status: "active",
        },
        {
            npk: "189",
            nama: "Alma Stout",
            no_hp: "+6286456852630",
            email: "almastout@aiia.id",
            alamat: "Tual",
            tgl_masuk: "2018-02-08",
            status: "nonactive",
        },
        {
            npk: "190",
            nama: "Jane Hicks",
            no_hp: "+6285657613631",
            email: "janehicks3553@aiia.co",
            alamat: "Semarang",
            tgl_masuk: "2017-05-14",
            status: "active",
        },
        {
            npk: "191",
            nama: "Wallace Livingston",
            no_hp: "+6287542242750",
            email: "wallacelivingston@aiia.co",
            alamat: "Banjarmasin",
            tgl_masuk: "2021-01-14",
            status: "nonactive",
        },
        {
            npk: "192",
            nama: "Ryan Cunningham",
            no_hp: "+6287457443789",
            email: "ryancunningham@aiia.id",
            alamat: "Banda Aceh",
            tgl_masuk: "2021-02-22",
            status: "active",
        },
        {
            npk: "193",
            nama: "Moana Gay",
            no_hp: "+6282432829381",
            email: "moanagay5573@aiia.co",
            alamat: "Baubau",
            tgl_masuk: "2016-06-08",
            status: "nonactive",
        },
        {
            npk: "194",
            nama: "Kareem Aguirre",
            no_hp: "+6285215867567",
            email: "kareemaguirre5951@aiia.id",
            alamat: "Gorontalo",
            tgl_masuk: "2020-12-06",
            status: "nonactive",
        },
        {
            npk: "195",
            nama: "Brendan Wolf",
            no_hp: "+6287298537873",
            email: "brendanwolf7698@aiia.co",
            alamat: "Denpasar",
            tgl_masuk: "2023-02-06",
            status: "nonactive",
        },
        {
            npk: "196",
            nama: "Natalie Ellison",
            no_hp: "+6283175835794",
            email: "natalieellison3490@aiia.id",
            alamat: "Pontianak",
            tgl_masuk: "2016-05-11",
            status: "nonactive",
        },
        {
            npk: "197",
            nama: "Zena Ortiz",
            no_hp: "+6288807314502",
            email: "zenaortiz@aiia.co",
            alamat: "Manokwari",
            tgl_masuk: "2018-12-25",
            status: "nonactive",
        },
        {
            npk: "198",
            nama: "Jessica O'connor",
            no_hp: "+6284487588551",
            email: "jessicaoconnor3299@aiia.co",
            alamat: "Blitar",
            tgl_masuk: "2016-01-14",
            status: "active",
        },
        {
            npk: "199",
            nama: "Wang Horn",
            no_hp: "+6284546922304",
            email: "wanghorn@aiia.co",
            alamat: "Bitung",
            tgl_masuk: "2020-08-01",
            status: "active",
        },
        {
            npk: "200",
            nama: "Stewart Delacruz",
            no_hp: "+6286716517608",
            email: "stewartdelacruz1011@aiia.co",
            alamat: "Tanjung Pinang",
            tgl_masuk: "2019-07-02",
            status: "active",
        },
        {
            npk: "201",
            nama: "Melissa Bruce",
            no_hp: "+6288116131476",
            email: "melissabruce910@aiia.id",
            alamat: "Singkawang",
            tgl_masuk: "2023-06-05",
            status: "nonactive",
        },
        {
            npk: "202",
            nama: "Isaac Pierce",
            no_hp: "+6282468342813",
            email: "isaacpierce9501@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2024-01-26",
            status: "nonactive",
        },
        {
            npk: "203",
            nama: "Xaviera Jensen",
            no_hp: "+6288134342165",
            email: "xavierajensen7208@aiia.id",
            alamat: "Banda Aceh",
            tgl_masuk: "2021-11-28",
            status: "nonactive",
        },
        {
            npk: "204",
            nama: "Patricia Underwood",
            no_hp: "+6286447376726",
            email: "patriciaunderwood@aiia.id",
            alamat: "Tarakan",
            tgl_masuk: "2022-08-31",
            status: "nonactive",
        },
        {
            npk: "205",
            nama: "Brenden Dominguez",
            no_hp: "+6282574312166",
            email: "brendendominguez@aiia.co",
            alamat: "Tanjung Pinang",
            tgl_masuk: "2018-05-27",
            status: "active",
        },
        {
            npk: "206",
            nama: "Emery Conrad",
            no_hp: "+6287156661322",
            email: "emeryconrad4151@aiia.id",
            alamat: "Mamuju",
            tgl_masuk: "2017-07-18",
            status: "active",
        },
        {
            npk: "207",
            nama: "Ila Wiggins",
            no_hp: "+6283964829331",
            email: "ilawiggins@aiia.co",
            alamat: "Makassar",
            tgl_masuk: "2016-10-30",
            status: "nonactive",
        },
        {
            npk: "208",
            nama: "Len Hess",
            no_hp: "+6288877646865",
            email: "lenhess@aiia.id",
            alamat: "Tarakan",
            tgl_masuk: "2017-08-07",
            status: "nonactive",
        },
        {
            npk: "209",
            nama: "Hollee Hernandez",
            no_hp: "+6288961921295",
            email: "holleehernandez@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2024-03-17",
            status: "active",
        },
        {
            npk: "210",
            nama: "Orli Peterson",
            no_hp: "+6281862867064",
            email: "orlipeterson@aiia.id",
            alamat: "Bengkulu",
            tgl_masuk: "2021-09-22",
            status: "active",
        },
        {
            npk: "211",
            nama: "Dexter Fitzgerald",
            no_hp: "+6285183211332",
            email: "dexterfitzgerald9831@aiia.co",
            alamat: "Singkawang",
            tgl_masuk: "2018-03-10",
            status: "active",
        },
        {
            npk: "212",
            nama: "Rudyard Norris",
            no_hp: "+6283271781141",
            email: "rudyardnorris@aiia.co",
            alamat: "Bontang",
            tgl_masuk: "2021-07-06",
            status: "nonactive",
        },
        {
            npk: "213",
            nama: "Jasper Mooney",
            no_hp: "+6287113425543",
            email: "jaspermooney@aiia.id",
            alamat: "Central Jakarta",
            tgl_masuk: "2022-10-15",
            status: "nonactive",
        },
        {
            npk: "214",
            nama: "Cecilia Anderson",
            no_hp: "+6283975167528",
            email: "ceciliaanderson517@aiia.id",
            alamat: "Bengkulu",
            tgl_masuk: "2015-12-03",
            status: "nonactive",
        },
        {
            npk: "215",
            nama: "McKenzie Ortega",
            no_hp: "+6288878539461",
            email: "mckenzieortega@aiia.co",
            alamat: "Tanjung Pinang",
            tgl_masuk: "2018-06-12",
            status: "nonactive",
        },
        {
            npk: "216",
            nama: "Carol Weaver",
            no_hp: "+6284615314131",
            email: "carolweaver9032@aiia.id",
            alamat: "Bengkulu",
            tgl_masuk: "2015-12-14",
            status: "nonactive",
        },
        {
            npk: "217",
            nama: "Rama Gill",
            no_hp: "+6287323193639",
            email: "ramagill2190@aiia.id",
            alamat: "Mojokerto",
            tgl_masuk: "2018-03-01",
            status: "nonactive",
        },
        {
            npk: "218",
            nama: "Aaron Calhoun",
            no_hp: "+6287475214688",
            email: "aaroncalhoun@aiia.id",
            alamat: "Tual",
            tgl_masuk: "2020-04-10",
            status: "nonactive",
        },
        {
            npk: "219",
            nama: "Veronica Griffith",
            no_hp: "+6285736651855",
            email: "veronicagriffith@aiia.co",
            alamat: "Jakarta",
            tgl_masuk: "2022-08-22",
            status: "nonactive",
        },
        {
            npk: "220",
            nama: "Yardley Castaneda",
            no_hp: "+6284371412617",
            email: "yardleycastaneda5651@aiia.id",
            alamat: "Denpasar",
            tgl_masuk: "2016-04-13",
            status: "active",
        },
        {
            npk: "221",
            nama: "Tallulah Johnston",
            no_hp: "+6289442208453",
            email: "tallulahjohnston4293@aiia.id",
            alamat: "Binjai",
            tgl_masuk: "2019-08-28",
            status: "nonactive",
        },
        {
            npk: "222",
            nama: "Inga Flynn",
            no_hp: "+6289292642843",
            email: "ingaflynn@aiia.co",
            alamat: "South Jakarta",
            tgl_masuk: "2022-02-25",
            status: "nonactive",
        },
        {
            npk: "223",
            nama: "Jerome Sharpe",
            no_hp: "+6282233532538",
            email: "jeromesharpe9123@aiia.co",
            alamat: "Pangkalpinang",
            tgl_masuk: "2016-10-21",
            status: "active",
        },
        {
            npk: "224",
            nama: "Ora Wong",
            no_hp: "+6285376056838",
            email: "orawong@aiia.co",
            alamat: "Pekanbaru",
            tgl_masuk: "2018-04-04",
            status: "active",
        },
        {
            npk: "225",
            nama: "Maile Leon",
            no_hp: "+6280874980136",
            email: "maileleon5702@aiia.co",
            alamat: "Tarakan",
            tgl_masuk: "2018-08-05",
            status: "active",
        },
        {
            npk: "226",
            nama: "Noah Curtis",
            no_hp: "+6281851517314",
            email: "noahcurtis4859@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2018-05-16",
            status: "active",
        },
        {
            npk: "227",
            nama: "Kimberley Dominguez",
            no_hp: "+6288182633249",
            email: "kimberleydominguez5017@aiia.co",
            alamat: "Metro",
            tgl_masuk: "2019-10-05",
            status: "nonactive",
        },
        {
            npk: "228",
            nama: "Larissa Carey",
            no_hp: "+6286568306922",
            email: "larissacarey3513@aiia.co",
            alamat: "Blitar",
            tgl_masuk: "2019-12-08",
            status: "active",
        },
        {
            npk: "229",
            nama: "Rebekah Hunter",
            no_hp: "+6287519863885",
            email: "rebekahhunter@aiia.co",
            alamat: "Banda Aceh",
            tgl_masuk: "2022-01-31",
            status: "nonactive",
        },
        {
            npk: "230",
            nama: "Harper Grimes",
            no_hp: "+6281346271173",
            email: "harpergrimes@aiia.id",
            alamat: "Palangka Raya",
            tgl_masuk: "2019-05-18",
            status: "active",
        },
        {
            npk: "231",
            nama: "Coby Chandler",
            no_hp: "+6286853622385",
            email: "cobychandler6449@aiia.co",
            alamat: "Bengkulu",
            tgl_masuk: "2016-11-22",
            status: "nonactive",
        },
        {
            npk: "232",
            nama: "Hedley York",
            no_hp: "+6284278153141",
            email: "hedleyyork@aiia.co",
            alamat: "Palembang",
            tgl_masuk: "2020-03-27",
            status: "active",
        },
        {
            npk: "233",
            nama: "Slade Reed",
            no_hp: "+6284202675517",
            email: "sladereed@aiia.id",
            alamat: "Tarakan",
            tgl_masuk: "2017-03-25",
            status: "active",
        },
        {
            npk: "234",
            nama: "Barry Nunez",
            no_hp: "+6281847633821",
            email: "barrynunez1980@aiia.co",
            alamat: "Parepare",
            tgl_masuk: "2020-05-06",
            status: "nonactive",
        },
        {
            npk: "235",
            nama: "Anjolie Bishop",
            no_hp: "+6282298702119",
            email: "anjoliebishop8720@aiia.co",
            alamat: "Jayapura",
            tgl_masuk: "2022-10-09",
            status: "active",
        },
        {
            npk: "236",
            nama: "Shafira Hull",
            no_hp: "+6281409425249",
            email: "shafirahull@aiia.co",
            alamat: "Gorontalo",
            tgl_masuk: "2022-05-12",
            status: "nonactive",
        },
        {
            npk: "237",
            nama: "Yasir Wright",
            no_hp: "+6280612319676",
            email: "yasirwright4855@aiia.id",
            alamat: "Sawahlunto",
            tgl_masuk: "2017-08-12",
            status: "nonactive",
        },
        {
            npk: "238",
            nama: "Yoshi Dillard",
            no_hp: "+6283257955161",
            email: "yoshidillard@aiia.co",
            alamat: "Sungai Penuh",
            tgl_masuk: "2017-08-07",
            status: "nonactive",
        },
        {
            npk: "239",
            nama: "Justin Rice",
            no_hp: "+6283218864336",
            email: "justinrice488@aiia.co",
            alamat: "Denpasar",
            tgl_masuk: "2020-12-04",
            status: "nonactive",
        },
        {
            npk: "240",
            nama: "Colleen Melendez",
            no_hp: "+6285953427787",
            email: "colleenmelendez6344@aiia.co",
            alamat: "Pangkalpinang",
            tgl_masuk: "2017-12-28",
            status: "nonactive",
        },
        {
            npk: "241",
            nama: "Dacey Ayala",
            no_hp: "+6282647429491",
            email: "daceyayala3825@aiia.co",
            alamat: "Palu",
            tgl_masuk: "2022-01-18",
            status: "nonactive",
        },
        {
            npk: "242",
            nama: "Xavier Kline",
            no_hp: "+6283855372657",
            email: "xavierkline7765@aiia.id",
            alamat: "Tanjung Pinang",
            tgl_masuk: "2021-08-29",
            status: "active",
        },
        {
            npk: "243",
            nama: "Jelani Briggs",
            no_hp: "+6285542115173",
            email: "jelanibriggs@aiia.id",
            alamat: "Manokwari",
            tgl_masuk: "2016-07-21",
            status: "nonactive",
        },
        {
            npk: "244",
            nama: "Freya Oliver",
            no_hp: "+6283054567419",
            email: "freyaoliver4263@aiia.id",
            alamat: "South Jakarta",
            tgl_masuk: "2023-10-23",
            status: "active",
        },
    ]

    return data
}

export default getData
